tap 'homebrew/bundle'

brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'nodebrew'
brew 'tree'
brew 'jq'
brew 'curl'
brew 'git'
brew 'peco'
brew 'ruby-build'
brew 'rbenv'
brew 'vim'
brew 'wget'
brew 'mysql'
brew 'kubectl'
brew 'starship'
brew 'java'
brew 'mas'
brew 'guetzli'
brew 'nomad'
brew 'carthage'
brew 'grafana'
brew 'xcodegen'

cask 'visual-studio-code'
cask 'docker'
cask 'the-unarchiver'
cask 'sequel-pro'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'chromedriver'
cask 'google-japanese-ime'
cask 'intellij-idea'
cask 'skitch'
cask 'zoomus'
cask 'iterm2'
cask 'java'
cask 'dotnet-sdk'

mas "com.apple.dt.Xcode", id: 497799835
