name: install.sh

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      path: '~/'
    - name: install.sh
      run: ./install.sh
